### ISSUE TITLE
Boost depends on old strlib

### ISSUE THREAD

**Issue by halmusaibeli** [kobbled/Ka-Boost#4]
Boost file depends on an older version of the **Strings** lib.
Not sure what Boost does!
It can not be just deleted, it has a reverse dependency (e.g. KPI_SRS).

**Comment by halmusaibeli** [comment]
@kobbled

**Comment by kobbled** [comment]
This is deprecated, as well as `strlib`.  Comment out any instance of KPI_SPS in the old templates
